version: '2.0'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.data.mongodb.host" : "89.116.214.72",
              "spring.data.mongodb.port" : "27017",
              "spring.data.mongodb.database" : "admin"
            }'
    depends_on:
      - mongodb

volumes:
  mongodb_data: